### ISSUE TITLE
túramozgalom-kapcsolatok létrehozása

### ISSUE THREAD

**Issue by kolesar-andras** [kolesar-andras/turistautak-osm-api#11]
@nemethtamas írta egy [másik](https://github.com/kolesar-andras/turistautak-osm-api/issues/4) témához:

> A Turamozgalom paramétert tartalmazó utak kezelve vannak valamilyen módon? Lehetséges lenne az API-val erre szűrni, még ha csak egy lat/lon párokat tartalmazó szövegfájlt adna vissza, hiszen úgy már könnyen létre lehetne hozni egy kapcsolatot hozzá, ha betölti az ember egy rétegre, ha látom, melyik utak futnak alatta

Ezt úgy tervezem megoldani, hogy a turistajelzés-kapcsolatokat kialakító algoritmust felkészítem arra, hogy nézze a túramozgalom mezőt is, vagyis ebből is készítsen kapcsolatokat. Innentől kezdve aztán a jelzéseket összefűző algoritmus szépen összerakja ugyanúgy, mint a turistajelzéseket. Fontos még, hogy az útszakaszok összefűzése is vegye figyelembe ezt a mezőt, vagyis ne fűzzön össze olyat, ahol ez a mező különbözik, ahogyan a Label esetén is teszi.

Megnéztem a mező tartalmát:

	SELECT COUNT(*) AS darab, turamozgalom
	FROM turistautak.segments
	WHERE deleted=0
	GROUP BY turamozgalom
	ORDER BY COUNT(*) DESC
	LIMIT 30
	
	4482 	OKT
	1686 	AK
	1552 	RP-DDK
	1401 	MZ
	983 	KDP
	933 	DDP
	519 	BFKÉK
	436 	Szent Márton Gyalogos Túraút
	432 	KOh
	336 	FTV
	290 	HolVör
	282 	Móricz Zsigmond Emléktúra
	245 	Rómer Flóris Emlékút
	239 	Olajos körút
	233 	BKT
	150 	MU
	149 	Dornyay Béla emlékút
	135 	Kápolnák útja
	135 	MZ (Tass)
	134 	Móra túra tanösvény
	119 	MZ (Baja)
	93 	OKT,MU
	82 	MZ (Hajós)
	79 	Theodóra-Kékkő Tanösvény
	73 	Szent Erzsébet zarándokút
	72 	RP-DDK,MZ
	64 	Szent Imre vándorút
	63 	Források útja
	59 	OKT,HolVör	
	59 	Baradla-tanösvény

Úgy tűnik, hogy elég lesz a vesszők mentén felszabdalni, majd mehet is a name= címkébe.

**Comment by nemethtamas** [comment]
Ez így nagyon jó lenne, köszönöm!

És akkor még javasolnék egy plusz címkét is, ami automatikusan hozzáadódna, és jelezné, hogy ez túramozgalom, mert a route=hiking, type=route minden jelzett útra illeszkedik, nem lehet szűrni. A kitöltött name mezővel sem, mert a JOSM preset a jel címkét pakolja bele.
badge_movement=yes, vagy valami hasonlóra gondolok.

**Comment by kolesar-andras** [comment]
Ez a címke nehezen értelmezhető, keressünk jobb megkülönböztetést. Nem lenne elég, ha a jelzett plusz turistautak címkéinek hiányára keresnél? Például a jel kulcsra. 

* JOSM: route=hiking -jel
* overpass-turbo: route=hiking and jel is null
	
A fenti kereséssel megtaláltam például a [Fehér Szív útja](http://www.openstreetmap.org/relation/3888415) zarándokutat.

**Comment by kolesar-andras** [comment]
[Kész](https://github.com/kolesar-andras/turistautak-osm-api/commit/bbfa224ef15fc9dfb21fe308ccc738ded466eedd), próbáld ki!

**Comment by nemethtamas** [comment]
"vagyis ne fűzzön össze olyat, ahol ez a mező különbözik, ahogyan a Label esetén is teszi."

Akkor ezek szerint szándékos, hogy az FTV, és az IVV-vel közösen futó FTV részek külön kapcsolatba kerülnek? Mert most látok 1,2, 22, 28, és 47 tagú FTV kapcsolatot. Ahogy látom, a fonódó mozgalmaknál jönnek létre az alacsony elemszámú kapcsolatok.

**Comment by kolesar-andras** [comment]
Nem volt szándékos, hibásan működött. Az rendben volt hogy nem szabad összefűznie olyan *vonalakat*, amelyeken nem azonos túramozgalmak haladnak, mert akkor nem tudná később létrehozni rájuk a kapcsolatokat.

A hiba a ott volt, hogy a *kapcsolatok* összefűzése éppen azt a "jel" címkét nézte, ami a túramozgalmaknál üres volt, így ahol fonódtak, ott kettőnél több azonos (=üres) találkozása miatt nem fűzött. Javítottam, most már figyelmbe veszi a name-et, ha nincs jel.

**Comment by nemethtamas** [comment]
Igen, most működik, hamarosan ki is próbálom  élesben :)
