### ISSUE TITLE
Félig konvertált  adatok problémája ["Híd" probléma] - esetleg fixme= belegenerálása

### ISSUE THREAD

**Issue by ImreSamu** [kolesar-andras/turistautak-osm-api#12]
A levlistán is jelzett problémára -> figyelmetlenségből rengeteg[1]  félig felcímkézett import kerül be az OSM-be -   valami megoldást kellene találni ...

példa:
```josm
name=Híd
source=turistautak.hu
url=http://turistautak.hu/poi.php?id=....
```

[1] - jelenleg  az overpass wizard a  `“name="Híd" and source="turistautak.hu"  in Hungary` -ra  ->   7 db figyelmetlenségből átvitt POI-t ad.

Javaslat:
Valamilyen speciális konverziós címkét ( pl.  `fixme=` ) helyezünk el, ami figyelmeztet.

feltétel:
HA csak a   `name` + `source` + `url`  címke került kigenerálásra az objektumhoz, 
AKKOR  tegyen automatikusan egy `fixme="Tuhu-001 name=....   nem sikerült átkonvertálni "` címkét is az objektumhoz.

Miért?
* ha ez bekerül az adatbázisba, akkor könnyebb lekérdezni őket overpass-wizard-al.  
  például  overpass-wizard : 'source="turistautak.hu"  and fixme is not null  in Hungary`  

Megjegyzés: 
* a `"Tuhu-001"`  - egy warning kód rendszer lenne, hogyha lenne később egy másik is, akkor meg tudjuk különböztetni.

A másik hasznos dolog az lenne,  hogyha a JOSM-ban létrehoznánk egy ellenőrzési szabályt, ami ezekre figyelmeztet feltöltés előtt ( warning )
* https://help.openstreetmap.org/questions/28198/how-to-writechange-custom-josm-validator-rules

**Comment by kolesar-andras** [comment]
A TuHu rövidítéssel és a figyelmeztetések számozásával nem értek egyet.

A híd megoldására az alábbi [módosítást tettem](https://github.com/kolesar-andras/turistautak-osm-api/commit/0186efe8716f69aae896dbc3d1ad8c2ead217b6e): kap bridge=yes címkét, amitől a JOSM hibaellenőrzőtől két hibajelzést kis kap: bridge gyanús objektumon, bridge= egy ponton.

Hosszabb távon azt tervezem ([le is írtam](https://github.com/kolesar-andras/turistautak-osm-api/issues/3)), hogy a híd nem pontként fog lejönni, hanem megszakítja az alatta levő utat és ez kap rendes bridge=yes címkét.

**Comment by ImreSamu** [comment]
>A hidak kérdését már megoldottam.
>https://github.com/kolesar-andras/turistautak-osm-api/issues/12

A híd csak egy példa a "hiányzó  objektum típus problémának"   
A többi típust is kezelni kellene.

A híd mellett van még   
 *  "Itató"  : http://www.openstreetmap.org/node/3329072414
 *  "Fácánnevelő-telep" : http://www.openstreetmap.org/node/3329072411
 *  "Focipálya"  http://www.openstreetmap.org/node/3329072410
 *  "Kopjafa" http://www.openstreetmap.org/node/3329792476
 *   ....

**Comment by ImreSamu** [comment]
még ezeket találtam:
*  "Horhos" :  http://www.openstreetmap.org/node/3327682100 
*  "Kutyák!" :  http://www.openstreetmap.org/node/3329072418
*  "Gyaloghíd":  http://www.openstreetmap.org/node/3329792469

**Comment by kolesar-andras** [comment]
Beállítottam a fenti hat típus kezelését. Ez csak a jéghegy csúcsa, van még egy csomó ponttípus, amit még nem feleltettünk meg OSM címkékkel. Ezek mostantól egységesen landuse=fixme címkét kapnak, amire a JOSM figyelmeztetést ad.
