### ISSUE TITLE
jelezni OSM-ben dátumot és azonosítót a turistautak.hu-ról

### ISSUE THREAD

**Issue by ImreSamu** [kolesar-andras/turistautak-osm-api#2]
Javasolnám , hogy több metaadatot vegyen át az API.
pl. a forrás adat rögzítésének a dátumát , mivel nem mindegy, hogy 1 éves vagy 10 éves adatról van szó.  A mostani verzióban most csak a "source=turistautak.hu" - kerül át, és mintha ez az adat elveszne.

javaslat:

``` json
source=turistautak.hu
source:tuhu:date=YYYY-MM-DD     //    <--- datepart ( TuHu ´"Letrehozva"´) 
source:tuhu:ref=1021008          //    Tuhu ID 
```

indoklás:
- source:tuhu:date hasznos lehet
  -  más POI adatbázisok importja esetén, pl. hogyha egy étterem abban is benne van, de más néven, akkor lehet következtetni egyes esetekben, hogy melyik lehet a frissebb.  Vagy egy 1 éves országos gyógyszertárlistában  nem szerepel azon a környéken gyógyszertár, akkor tudjuk, hogy a TuHu forrást mikor rögzítették.  Ha 7 éve, akkor valószínűleg azért mert bezárták ..  
  - minőség-ellenőrzési riportok készítéséhez.    Overpass turbóval le lehet kérdezni az 5 évnél régebbi TuHu rögzítésű adatokat , amelyek nagyobb prioritást kapnának az újrafelmérésben.
- source:tuhu:ref hasznos lehet a két adatbázis mélyebb összekötésében.
  -  És  ha később javítunk a  tuhu->osm kulcs fordításon, akkor ezzel talán egyszerűbb átvezetni a változásokat, 
  - Ha  frissült a TuHu-s forrás,  akkor feltételezésem szerint ezzel egyszerűbb átvezetni az adatokat.

természetesen lehet más elnevezés is. ( pl. source:tuhu_id  )

más importoknál is általában átveszik ezeket az adatokat ( http://wiki.openstreetmap.org/wiki/BAGimport 
- ref:bag=  "bagid as available in BAG" //  Original bag id from field PAND_ID useful for future updates
- source:date="YYYY-MM-DD"    //    Date of the release of the imported BAG data
  )

**Comment by kolesar-andras** [comment]
Két részre bontom a javaslatot.

### azonosító

Tegnap grin is [felvetette](http://turistautak.hu/forum.php?action=thread&id=osm&message_id=449608) ugyanezt a turistautak.hu osm fórumán. Ezt válaszoltam neki:

Az ID= belekerül, a kulcs neve átírható akár tömegesen is ref:turistautak.hu=-ra, de én ezt nem erőltetném. Az osm-en zavaró lenne a vonalak egyesítésénél, ráadásul a turistautak.hu-n is ugyanúgy archiválódni tud azonosító a vonalak egyesítésénél és vágásánál, ahgyan az osm-en is történik.

A poi-k esetében az url mezőben szerepel az id, ott értelme is van. Formátuma: url=http://turistautak.hu/poi.php?id=22705

Futottunk egy kört azzal kapcsolatban, hogy jó-e hogy az url mezőben szerepel (csak) az azonosító. Erre ez volt a válaszom:

Erősen redundáns lenne az url-el, ami géppen ugyanolyan könnyen kezelhető. Emberi felhasználásra az url könnyebb, ezért választottam.

### dátum

Sok dátum szerepel a POI táblában, ebből kettőt hoz le az API:

	'Letrehozva' => $myrow['dateinserted'],
	'Modositva' => $myrow['dateuploaded'],

Az összes dátummező:

* dateposted: bejelentő által az űlapon megadott dátum
* dateinserted: ekkor került az adatbázisba
* datemodified: ekkor módosult utoljára a webfelületről
* dateuploaded: ekkor töltötte fel utoljára térképszerkesztő
* datelocated: koordináta nélkül feltöltött poi ekkor kapott koordinátát
* datedeleted: törlés dátuma

Ezen felül lehetnek még megjegyzések, bár elég kis számban (11898 darab megjegyzés a 164242 poihoz):

* date: megjegyzés dátuma, ahogyan a felhasználó megadta
* dateinserted: ekkor került az adatbázisba
* datemodified: ekkor módosult utoljára

A fentieket áttekintve annyival egészíteném ki az algoritmust, hogy módosítás dátumának a sok felsorolt közüli legkésőbbi dátumot adja meg.

Kérdés viszont, hogy van-e értelme átvenni ezt az adatot, amikor egyrészt lekérdezhető a turistautak.hu-ról, másrészt attól még jó eséllyel ott van a pont, hogy tíz éve bent van az adatbázisban és nem szorult módosításra.

A templom, buszmegálló, kilométerkő, határkő, kereszt eléggé állandó dolog, változékonysága alacsony. A fent hivatkozott vértesboglári templom 2007 óta szerepel az adatbázisban, módosítás és megjegyzések nélkül, 1810 óta ma is áll.

A poi korára vonatkozóan amúgy az azonosító is választ ad, mivel szigorúan monoton növekvő számsor. Az elmúlt évek legelső azonosítói:

	SELECT DATE_FORMAT(dateinserted, '%Y'), MIN(id)
	FROM poi
	GROUP BY DATE_FORMAT(dateinserted, '%Y')
	ORDER BY DATE_FORMAT(dateinserted, '%Y');

	2002 	1
	2003 	76
	2004 	992
	2005 	2062
	2006 	5998
	2007 	16195
	2008 	37450
	2009 	63200
	2010 	84731
	2011 	107404
	2012 	131460
	2013 	149145
	2014 	164390
	2015 	175578

**Comment by ImreSamu** [comment]
köszönöm a részletes választ.

azonosító :
* Akkor ha a POI -nál megvan. ez nekem már megfelelő. 
* Vonalaknál ha akarunk olyan statisztikát csinálni, hogy mennyivel lettek eltolva a vonalak 
   pl  Hausdorff distance  / http://gis.stackexchange.com/questions/116512/similarity-between-two-or-more-trajectories , akkor szükség lehet az egyértelmű összerendeléshez, egyébként ehhez nem ragaszkodom annyira, habár szerintem hasznos lehet.    ( én beleraknám ezt is. )

dátum: 
*  A legutolsó módosítási dátum - ez így tökéletes lenne.  
*  a későbbi 2-3-4-5 év múlva várható  egyszerű overpass lekérdezéshez szerintem jól jöhet.  
   Nem kell a 2 adatbázis összekapcsolásán fáradozni ( ami már extrém haladó feladat )
   Az  overpass-wizard -al egy kezdő is tud lekérdezéseket csinálni.  
*  ezen kívül, hogyha a vonalaknál nincs megoldva az API-s összekapcsolás  lehetősége,  
   (mert nem lesz   "id" ) , akkor egyáltalán nem lesz olyan egyszerű ezen információ előállítása.
*  Ez az információ szerintem praktikusabb.  
    A következő pár évben várható importálásokat egyszerűsítheti ..  

>"Kérdés viszont, hogy van-e értelme átvenni ezt az adatot, amikor egyrészt
> lekérdezhető a turistautak.hu-ról, 

A szerencsés az lenne, hogy a későbbi adat importok végrehajtóinak nem kellene az OSM mellett a turistautak.hu-ra is rákapcsolódnia és annak az adatszerkezetébe is belemélyedni.
Előfordulhatnak olyan esetek, hogy valaki az 1 -1,5 éves saját feljegyzését szeretné felvinni az OSM-be, de közben valaki beimportált oda egy ugyanolyan objektumot, ami viszont pár dologban eltér, és jönnek a dilemmák. Melyik áll közelebb a valósághoz?
Egy külföldi aki eltöltött nálunk 3 hetet  nem fog rácsatlakozni  majd a turistautak.hu -ra emiatt, mivel nem hiszem, hogy angolul vagy németül is minden részletet ledokumentálnánk. Majd valahogy dönt, de nem biztos, hogy a legjobb döntést hozza majd meg.

Tudom ezek extrém esetek, de ahogy én észrevettem az adatimport mellett az adat állapotára vonatkozó időponti adat is  beimportálásra kerül.

**Comment by kolesar-andras** [comment]
Vonalaknál és felületeknél nincs értelme átvenni azonosítókat. Nagyon változékony osm-en és a turistautak.hu-n egyaránt, összevonáskor és vágáskor egyaránt bukik az egész.

A dátummal ugyanez a helyzet vonalaknál és felületeknél. Elég odébb tolni egy töréspontot és máris frissül a dátuma. Nem lesz frissebb ettől a felmérése, a letárolt adat tökéletesen értelmetlen. POI esetén is előfordulhat, hogy a szerkesztő tol rajta fél métert, de ettől még nem járt akkor a helyszínen, hogy megnézze, megvan-e még.

Ha lenne benne mondjuk survey:date, akkor azt letárolnám, de nincs. Az osm-en lehetne ilyen címke, de ezt se nagyon tölti senki. Ha lenne belőle survey:date-first és survey:date-last, akkor a first nem lenne különösebben érdekes, a last-ot pedig minden bejárásnál módosítani unalmas és pazarló munkában és tárhelyben egyaránt, ráadásul többnyire redundáns a nyomvonalak dátumával.

Írtad a source:date vagy source:tuhu:date kulcsokat, utóbbit nem támogatom, legfeljebb source:turistautak.hu:date vagy date:turistautak.hu formában. Kérdés, hogy ezt hogyan értelmezik, akik nem olvassák el az importálás dokumentációját:

* ekkor vettük át a turistautak.hu-ról (felesleges, mert az osm adatbázisban való megjelenés dátumával azonos)
* ekkor került fel a turistautak.hu-ra (dateinserted)
* ekkor módosult utoljára a turistautak.hu-n az átvétel előtt (dateuploaded, illetve a legutolsó dátum)

Egyiknek sincs értelme szerintem. Nem jutsz érdemi információhoz általa. Attól nem pontosabb, hitelesebb vagy értékesebb egy objektum, hogy későbbi a dátuma.

**Comment by ImreSamu** [comment]
elméleti példa:

Külföldi német turista, nyári európai körútja során (2014-08-20 -.én)   egy hazai vidéki város utcájában is járt, és felmérést végzett az adott utcában.   ( alapos fotók, videókamera , jegyzetek )
a nyári adatok feldolgozásában ehhez a részhez 2015 március 12.-én ért el.

De közben már korábban a ( felmérés és a rögzítés között ) - 2015-02-25 -én  user:OSM_importer_A  beimportálta ugyanazt az adatot az osm-be  

Ezt
```json
ID=92468
Label=Bagoly vendéglő (éjfélig)
Letrehozta=xxxxxx
Letrehozva=2010-05-08 05:41:11
Magassag=0
Modositotta=zzzzzz
Modositva=2010-05-16 00:25:48
Type=0xa103 étterem
[----------]=[----------]
amenity=restaurant
name=Bagoly vendéglő (éjfélig)
source=turistautak.hu
url=http://turistautak.hu/poi.php?id=92468
```

A "külföldi német turista" 2015 március 12.-én   ezt látja az adott helyen az osm adatbázisban:
```json
amenity=restaurant,
name=Bagoly vendéglő (éjfélig),
source=turistautak.hu,
url=http://turistautak.hu/poi.php?id=92468

timestamp=2015-02-25T16:10:04Z
user=OSM_importer_A 
```

Viszont ő az adott helyen anno egy sörözőt látott! 
Csak annyit tud biztosan, hogy az adott objektum 2014-08-20 -én söröző volt!
( fotója, videója van róla és nincs étterem egyáltalán, amivel összetéveszthetné. ) 
Megnézi az URL-t http://turistautak.hu/poi.php?id=92468  
* de azt nem érti ( nyelvi gondok ) 
* és amúgy is csak a "Letrehozva" van feltüntetve a weboldalon.

Vagyis nem lesz elég információja, hogy biztosan eldöntse, hogy átvezesse-e a változást vagy sem.
hiszen valaki 2015-02-25 -én felvett egy másmilyen állapotot.

Ha viszont a source:date=2010-05-16 - et is látja benne, 
akkor biztosan tudja, hogy az övé a frissebb információ és megmódosíthatja a POI-t söröző-re.

vagyis az ideális az lenne, hogyha ezt látná.

```json
amenity=restaurant,
name=Bagoly vendéglő (éjfélig),
source=turistautak.hu,
source:date=2010-05-16
url=http://turistautak.hu/poi.php?id=92468

timestamp=2015-02-25T16:10:04Z
user=OSM_importer_A 
```

A source:date=2010-05-16  -nek itt csak annyi jelentése van, 
hogyha ez után mértél fel ott, akkor nyugodtan módosítsd meg az adatot.
Ha ez előtt, akkor pedig NE! 

Elhúzódó importoknál szerintem hasznos ez az információ.
És ha esetleg az MTSZ-el lesz folyamatos adatcsere ( álmodozás ) ,
akkor az ütköző turista útvonalaknál hasonlóan el tudjuk dönteni, hogy melyik lehet a frissebb.

Vagyis emiatt javasolnám a "Source:date=YYYY-MM-DD" -berögzítését, ahogy más importoknál is előfordul.
http://wiki.openstreetmap.org/w/index.php?search=source%3Adate%3DYYYY-MM-DD&title=Special%3ASearch


természetesen
- wiki page kell "source=turistautak.hu" -ról ( angolul és magyarul )
- és ha nem "source:date" -lesz, a kulcs neve, akkor arról is.
és ott egyértelműen le kell írni, hogyha a saját felmérés ideje > "source:date" akkor biztosan módosíthatja,
egyébként  javasolt a valamilyen resurvey címke.
 
Vagyis ha az [ átlag user felmérése és a rögzítése között ]   valaki beimportált valami adatot, akkor legyen valami kapaszkodó  a döntéshez.

**Comment by kolesar-andras** [comment]
Pontosan azért *nem* ajánlom átvenni, mert nincs szoros összefüggés a dátum és a felmérés között. Szerencsés esetben közel esik a felméréshez, de ha 2014 őszén szeptemberében valaki távolabb tolta a poit az utcától, akkor megtévesztő lesz az adat.

Megnéztem egy kiseb elemszámú importot, [source:date=2011-12-23](http://overpass-turbo.eu/s/7uK). Rejkjavik buszmegállóit importálták [2012-02-06-án](http://www.openstreetmap.org/changeset/10599498) egy excel tábla alapján, amelyben nem volt dátum soronként, ez nyilván a táblázat keltének napja.

Ráböktem véletlenszerűen az [egyikre](http://www.openstreetmap.org/node/1619587104/history#map=16/64.1318/-21.8899), azóta már a #6 verziónál jár. Kapott egy csomó hasznos címkét, viszont kit érdekel a source:date? Az előzményekből bármikor megnézhető, hogy az első változat melyik módosításcsomaghoz kapcsolódik és mikor készült.

Ha van másnak is véleménye a témáról, várjuk hozzászólását.

**Comment by BathoryPeter** [comment]
Egyetértek veled, én sem venném át a dátumot.
