### ISSUE TITLE
szűrhető letöltési lehetőség országos importáláshoz

### ISSUE THREAD

**Issue by kolesar-andras** [kolesar-andras/turistautak-osm-api#5]
Készíthetnénk egy olyan változatot az apira, ami adott szűrőfeltételek szerint tölt le. Ez működhetne pontosan ugyanúgy, mint ahogyan az overpass-turbo adja át a lekérést a JOSM távirányítójának:

Így hívja a böngésző a távirányítót:

	GET /import?url=http%3A%2F%2Foverpass-api.de%2Fapi%2Finterpreter%3Ffixme%3DJOSM-ticket-8566%26data%3D%252F*%250AThis%2520has%2520been%2520generated%2520by%2520the%2520overpass-turbo%2520wizard.%250AThe%2520original%2520search%2520was%253A%250A%25E2%2580%259Camenity%253Dhunting_stand%25E2%2580%259D%250A*%252F%250A%255Bout%253Axml%255D%252F*fixed%2520by%2520auto%2520repair*%252F%255Btimeout%253A25%255D%253B%250A%252F%252F%2520gather%2520results%250A(%250A%2520%2520%252F%252F%2520query%2520part%2520for%253A%2520%25E2%2580%259Camenity%253Dhunting_stand%25E2%2580%259D%250A%2520%2520node%255B%2522amenity%2522%253D%2522hunting_stand%2522%255D(46.992431036151324%252C17.66738891601562%252C47.2090739013689%252C18.172760009765625)%253B%250A%2520%2520way%255B%2522amenity%2522%253D%2522hunting_stand%2522%255D(46.992431036151324%252C17.66738891601562%252C47.2090739013689%252C18.172760009765625)%253B%250A%2520%2520relation%255B%2522amenity%2522%253D%2522hunting_stand%2522%255D(46.992431036151324%252C17.66738891601562%252C47.2090739013689%252C18.172760009765625)%253B%250A)%253B%250A%252F%252F%2520print%2520results%250Aout%2520meta%253B%252F*fixed%2520by%2520auto%2520repair*%252F%250A%253E%253B%250Aout%2520meta%2520qt%253B%252F*fixed%2520by%2520auto%2520repair*%252F
	Host: 127.0.0.1:8111

JOSM meghívja az *url* paraméterben megadott címet:

	GET /api/interpreter?fixme=JOSM-ticket-8566&data=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Camenity%3Dhunting_stand%E2%80%9D%0A*%2F%0A%5Bout%3Axml%5D%2F*fixed%20by%20auto%20repair*%2F%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Camenity%3Dhunting_stand%E2%80%9D%0A%20%20node%5B%22amenity%22%3D%22hunting_stand%22%5D(46.992431036151324%2C17.66738891601562%2C47.2090739013689%2C18.172760009765625)%3B%0A%20%20way%5B%22amenity%22%3D%22hunting_stand%22%5D(46.992431036151324%2C17.66738891601562%2C47.2090739013689%2C18.172760009765625)%3B%0A%20%20relation%5B%22amenity%22%3D%22hunting_stand%22%5D(46.992431036151324%2C17.66738891601562%2C47.2090739013689%2C18.172760009765625)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20meta%3B%2F*fixed%20by%20auto%20repair*%2F%0A%3E%3B%0Aout%20meta%20qt%3B%2F*fixed%20by%20auto%20repair*%2F
	Host: overpass-api.de

Ezen a [címen](http://overpass-api.de/api/interpreter?fixme=JOSM-ticket-8566&data=%2F*%0AThis%20has%20been%20generated%20by%20the%20overpass-turbo%20wizard.%0AThe%20original%20search%20was%3A%0A%E2%80%9Camenity%3Dhunting_stand%E2%80%9D%0A*%2F%0A%5Bout%3Axml%5D%2F*fixed%20by%20auto%20repair*%2F%5Btimeout%3A25%5D%3B%0A%2F%2F%20gather%20results%0A(%0A%20%20%2F%2F%20query%20part%20for%3A%20%E2%80%9Camenity%3Dhunting_stand%E2%80%9D%0A%20%20node%5B%22amenity%22%3D%22hunting_stand%22%5D(46.992431036151324%2C17.66738891601562%2C47.2090739013689%2C18.172760009765625)%3B%0A%20%20way%5B%22amenity%22%3D%22hunting_stand%22%5D(46.992431036151324%2C17.66738891601562%2C47.2090739013689%2C18.172760009765625)%3B%0A%20%20relation%5B%22amenity%22%3D%22hunting_stand%22%5D(46.992431036151324%2C17.66738891601562%2C47.2090739013689%2C18.172760009765625)%3B%0A)%3B%0A%2F%2F%20print%20results%0Aout%20meta%3B%2F*fixed%20by%20auto%20repair*%2F%0A%3E%3B%0Aout%20meta%20qt%3B%2F*fixed%20by%20auto%20repair*%2F) az overpass api kiad egy .osm fájl, amit a JOSM megjelenít.

A feladat tehát kettős:

* kell egy webfelület, ahol okosan kiválasztható, hogy mit szeretnél letölteni
* a kapott url-t ki kell szolgálnia az apinak

Az első felének nem kell a turistautak.hu-n lennie, akár egy wikiben is elhelyezhetünk hivatkozásokat, például:

	http://turistautak.hu/api/map?poi=magasles
	http://turistautak.hu/api/map?line=kanyarodás+tiltás

Ilyen szűrés a befoglaló téglalapos letöltésbe is lehető, ha a paramétereket az api címébe szúrjuk:

	http://turistautak.hu/api-poi=magasles

**Comment by kolesar-andras** [comment]
Megvalósítottam a típus szerinti szűrhetőséget.

Általános szintaktika a /api/0.6/map? hívásánál GET paraméterként:

	poi=magasles
	poi=0xaa10
	poi=43536
	line=folyó
	line=kanyarod%C3%A1si%20tilt%C3%A1s
	polygon=bokros
	
A paraméterek a PHP által tömbösített formában felsorolhatók, logikai VAGY művelettel értendők:

	poi[]=magasles&poi[]=kereszt
	
Ugyanezek a paraméterek megadhatók az api címében is és itt is fűzhetők. A paramétereket & helyett - választja el.

	http://turistautak.hu/api-poi=magasles
	http://turistautak.hu/api-poi=magasles-poi=kereszt

Ha bármire van szűrés, akkor csak az a típus jön le. Ha nem kérsz vonalakat és felületeket, akkor nem jönnek. Ha csak a poikat szeretnéd, de abból összeset:

	http://turistautak.hu/api-poi
	
Feltételessé tettem a befoglaló téglalap szerinti szűrést, így a "map" lekérés eddigi egyetlen paramétere nem kötelező már. Ennek az a pratkikus eredménye, hogy könnyen lekérhető egy vagy több típus teljes állománya:

	http://turistautak.hu/api-poi=barlang/map
	http://turistautak.hu/api/map?poi=barlang
	
Hasonló példa vonalakra, a #1-ben felvetett kanyarodás-tiltások országos letöltésére, ékezetes betűk urlencode formában:

	http://turistautak.hu/api/map?line=kanyarodás+tiltás

**Comment by nemethtamas** [comment]
Most szedtem le a forrásokat, ott akadtam bele egybe, aminek az  node id-je nullát kapott, ezért a josm nem töltötte be:
<node id="-0000000000000000" lat="0.0000000" lon="0.0000000">
<tag k="Type" v="0xa202 forrás" />
<tag k="Label" v="Bonyi-kút .." />
<tag k="ID" v="128341" />

Persze, ki tudom törölni kézzel, de jobb lenne, ha generáláskor már nem kerülne bele.

**Comment by kolesar-andras** [comment]
Köszönöm a jelzést, [javítottam](https://github.com/kolesar-andras/turistautak-osm-api/commit/d6a16ac6dcc96ebef0d3641d1d6e1464fd8fabf5). Mostantól szűrőfeltétel a pontokra, hogy nem lehet nullás a koordinátájuk, mert akkor az azonosítója is csupa nulla lenne.

Egyúttal elgondolkodtam a pontok azonosítójának képzésén, írtam egy javaslatot a módosítására (#14)

**Comment by kolesar-andras** [comment]
A tesztelés során először poi=forras formában írtam a szűrést, amire üreset adott vissza, mert a típus neve forrás (ékezetesen). Ezért [kiegészítettem](https://github.com/kolesar-andras/turistautak-osm-api/commit/dc8f4e3bb976b63d9bd20c0eafa16c2cd2c87057) a programot a megadott típusnevek ékezettelenítésével összehasonlítás előtt, így most már működik a szűrés ékezet nélkül is.

**Comment by nemethtamas** [comment]
Ez a két poi a szűrhető API-n letöltve keresztül mért kapott vajon fixme=position címkét?
http://turistautak.hu/poi.php?id=26975
http://turistautak.hu/poi.php?id=26972

**Comment by nemethtamas** [comment]
Rájöttem, a tuhus nevükben szerepel a végén két pont

**Comment by kolesar-andras** [comment]
Úgy van. Amúgy az API ugyanúgy címkéz, akár típus szerint szűröd, akár befoglaló téglalappal, akár mindkettővel.
